### ISSUE TITLE
Override service config without excessive templating

### ISSUE THREAD

**Issue by kevb** [vudknguyen/swarm-pack#6]
Consider a simple pack template such as this:

```
---
version: '3.3'

services:
  portainer:
    image: "{{ image.repository }}:{{ image.tag }}"
    deploy:
      labels:
        - "swarm-sync.managed=true"
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
      placement:
        constraints:
          - node.role == manager
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Here, the pack developer made a decision that Portainer should be constrained on a manager node.

But what if I decide to connect Portainer to Docker via an HTTP API? I no longer need to constrain it to manager nodes only.

I could improve the template, for example:

```
      placement:
        constraints:
          {% if constrain_to_manager %}
          - node.role == manager
          {% endif %}
```

Or I could get even more clever, and allow an array of placement constraints in the values. This could get more and more complex, anticipating all the various scenarios. And this is only one thing - placement constrains - there are many more. The template will grow and grow...

What if we had a way to allow overriding or extending the template without the pack developers anticipating all use-cases in advance?

Some ways we could approach this:

 - Could we allow some specific overrides? (e.g)

`--service-placement-constraint portainer="node.role == manager"`

- Could we allow merging another YML file into the template? E.g.
https://github.com/dacut/Assemyaml/ (would still be combined with nunjucks)

Maybe this isn't a problem at all and templating will solve it? Needs some more thought...
